GRANT RELOAD, FLUSH_TABLES, LOCK TABLES, SELECT, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT
ON *.* TO 'appuser'@'%';

GRANT INSERT, UPDATE, DELETE, EXECUTE ON myappdb.* TO 'appuser'@'%';

FLUSH PRIVILEGES;